import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { AgentApi, ServiceSummary } from '../core/agent-api.service';

@Component({ standalone: true, template: `
  <section class="route-heading"><span class="eyebrow">SERVICE CONTROL CENTER</span><h1>Services</h1><p>Issue one configured service command at a time. “Command sent” becomes success only after the Agent confirms its final state.</p></section>
  @if (message(); as notice) { <p class="status-message" role="status">{{ notice }}</p> }
  <section class="service-summary"><article class="instrument-panel"><span class="eyebrow">WATCHLIST</span><strong>{{ services().length }}</strong><small>Configured services</small></article><article class="instrument-panel"><span class="eyebrow">MONITOR</span><strong>5s</strong><small>Agent-side polling</small></article><article class="instrument-panel"><span class="eyebrow">CONTROL</span><strong>Admin</strong><small>Loopback-only Agent</small></article></section>
  <section class="service-deck instrument-panel"><div class="panel-heading"><div><span class="eyebrow">LIVE CATALOG</span><h2>Configured services</h2></div><button type="button" (click)="refresh()" [disabled]="loading()">Refresh state</button></div>
    @if (loading() && !services().length) { <p class="mono">LOADING AGENT STATE</p> } @else if (!services().length) { <p>No services are configured for this Agent.</p> } @else { <div class="service-grid">@for (service of services(); track service.serviceId) { <article class="service-card"><div class="service-card-head"><div><span class="eyebrow">WINDOWS SERVICE</span><h3>{{ service.displayName }}</h3></div><span class="service-state" [attr.data-state]="service.state">{{ stateLabel(service.state) }}</span></div><p>{{ service.lastChecked.detail }}</p><time class="mono">{{ service.lastChecked.lastCheckedUtc || 'Not checked' }}</time>@if (service.lastOutcome) { <p class="service-outcome" role="status">{{ service.lastOutcome }}</p> }<div class="service-actions"><button type="button" (click)="command(service, 'start')" [disabled]="!allows(service, 'start')" [attr.aria-label]="'Start ' + service.displayName">Start</button><button type="button" (click)="command(service, 'stop')" [disabled]="!allows(service, 'stop')" [attr.aria-label]="'Stop ' + service.displayName">Stop</button><button type="button" (click)="command(service, 'restart')" [disabled]="!allows(service, 'restart')" [attr.aria-label]="'Restart ' + service.displayName">Restart</button></div></article> }</div> }
  </section>
`, })
export class ServicesPageComponent implements OnInit, OnDestroy {
  private readonly api = inject(AgentApi); private events: EventSource | null = null; private reconnect: ReturnType<typeof setTimeout> | null = null;
  protected readonly services = signal<ServiceSummary[]>([]); protected readonly loading = signal(false); protected readonly message = signal('');
  async ngOnInit(): Promise<void> { await this.refresh(); this.connect(); }
  ngOnDestroy(): void { this.events?.close(); if (this.reconnect) clearTimeout(this.reconnect); }
  async refresh(): Promise<void> { this.loading.set(true); try { this.services.set(await this.api.get<ServiceSummary[]>('/services')); } catch { this.message.set('Service state is unavailable. Check the Agent connection and refresh.'); } finally { this.loading.set(false); } }
  async command(service: ServiceSummary, action: 'start' | 'stop' | 'restart'): Promise<void> { if (!this.allows(service, action)) return; try { const updated = await this.api.mutate<ServiceSummary>('post', `/services/${service.serviceId}/actions`, { action, idempotencyKey: crypto.randomUUID() }); this.replace(updated); this.message.set(`${action[0].toUpperCase()}${action.slice(1)} command sent for ${service.displayName}. Awaiting Agent confirmation.`); } catch { this.message.set(`The ${action} command for ${service.displayName} was not accepted.`); } }
  protected allows(service: ServiceSummary, action: 'start' | 'stop' | 'restart'): boolean { return service.state !== 'transitioning' && service.allowedActions.includes(action); }
  protected stateLabel(state: ServiceSummary['state']): string { return state === 'notFound' ? 'Not found' : state[0].toUpperCase() + state.slice(1); }
  private connect(): void { this.events?.close(); this.events = new EventSource('/api/v1/events'); this.events.addEventListener('services', (event) => this.services.set(JSON.parse((event as MessageEvent<string>).data) as ServiceSummary[])); this.events.onerror = () => { this.events?.close(); if (!this.reconnect) this.reconnect = setTimeout(() => { this.reconnect = null; void this.refresh().then(() => this.connect()); }, 1000); }; }
  private replace(updated: ServiceSummary): void { this.services.update((items) => items.map((item) => item.serviceId === updated.serviceId ? updated : item)); }
}
