<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PosAdminTool.Application\PosAdminTool.Application.csproj" />
    <ProjectReference Include="..\PosAdminTool.Domain\PosAdminTool.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlaUI.UIA3" Version="4.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
    <PackageReference Include="System.Drawing.Common" Version="10.*" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.*" />
  </ItemGroup>

</Project>
